{% set name = "setfit" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setfit-{{ version }}.tar.gz
  sha256: 8b92eaa645ae80ee38e56a628d1e5a1f32364db8855b8e05ca3c71dccf0f4231

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - datasets >=2.3.0
    - sentence-transformers >=2.2.1
    - evaluate >=0.3.0

test:
  imports:
    - setfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SetFit/setfit
  summary: Efficient few-shot learning with Sentence Transformers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
